platform :ios, '13.0'

target 'EveryDay' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Resolver', :git => 'https://github.com/hmlongco/Resolver', :branch => 'develop'

end
